### PR TITLE
Czech translation

### PR DESCRIPTION
**Pull request by almasy**

### CODE REVIEW

**Comment by almasy** [comment]
@elecfreaks1, @xuhow - Hi! Is there something I could do to promote a merge of this pull request? E.g. in case something's missing, please let me know.

**Comment by almasy** [comment]
Added translation for new setServo method

**Comment by lobodpav** [comment]
Hey guys. My son would really use the Czech translation as he's young and can't speak English yet. Is there any issue merging the PR?

I was also thinking about buying more of your stuff for my kids for Christmas. However, given there has been no response from you for more than a year, it seems like no one maintains the product after releasing it. That just undermines the trust in the company, to be honest.

**Comment by almasy** [comment]
@lobodpav - hmm, seems like they actually did some updates in last few months... I'll look at the changes and update the translations to match the current state...

I just haven't noticed the recent changes, as I didn't setup any watch notifications and ElecFreaks didn't respond to the pull request for a very long time (as you've stated yourself).

**Comment by lobodpav** [comment]
@almasy Yeah, I noticed some activity too. But why do they ignore incoming PRs when good folks like you are trying to help? That is a shame.

**Comment by elecfreaks1** [comment]
@almasy @lobodpav 
Hello!

Firstly, I would like to extend our sincerest apologies on behalf of Elecfreaks. We have noticed that your Pull Request (PR) regarding the Czech translation has not received a response for quite some time. This is certainly not the impression we wish to leave with valued contributors like yourself, and for that, we are truly sorry.

We understand that your son needs the Czech version, and our delay in responding has caused inconvenience. Please allow me to explain why this PR has not yet been processed. In the past, we encountered issues where community-submitted PRs, which included functional changes, led to unforeseen bugs and compatibility problems with the latest versions of our products. To prevent such occurrences, we have since adopted a more cautious approach and established an internal review process for all PRs to ensure the stability, security, and compatibility of our products.

However, we greatly value community contributions, especially those that make our products accessible to a wider audience, such as language translations. To address your translation request more effectively, we would like to communicate with you directly. If you are willing, please provide us with an email address. We will send you a translation template, and once you complete the Czech translation, you can return it to us. Our team will then work to integrate it into the project as quickly as possible.

Additionally, we are honored that you are considering purchasing more of our products as Christmas gifts for your children. Please rest assured that we are committed to improving the quality of our customer service and support to ensure that you and your family enjoy the best possible experience with our products.

Once again, we apologize for the oversight and appreciate your patience and understanding. We look forward to continuing to serve you with excellence.

**Comment by lobodpav** [comment]
@elecfreaks1 Thanks for coming back to us. I plan to buy quite some robots for my whole family including accessories, so I needed to be sure there is some level of support from you guys so I won't buy a "dead" product again (happened to me a few times in the past 😞).

However, yesterday, I learned how amazing the `MakeCode` platform is — one can fork a repo, translate it, and provide others with a link to install the translated extension. That's just awesome.

Anyway, getting PRs merged is best for the community to benefit from the translation.

Even though I do not understand why you don't utilise the amazing code review capability GitHub offers (I use it with my team every day) and even though translating into some template would be definitely more difficult than translating 2 JSON files 😉 , I am willing to translate it the way you want.

You can contact me using the email on my GitHub profile.
 such an amazing code review capabilities that must be way easier to use than

**Comment by almasy** [comment]
@elecfreaks1 - Hi. I've created another pull request which is now in-sync with the latest contents of your repository.

Btw, I've noticed that the default localisation files are missing all of the PID subsection functions/blocks (even though the Chinese ones do contain those). Is this on purpose or will they be added later on?

**Comment by almasy** [comment]
@lobodpav 
> Even though I do not understand why you don't utilise the amazing code review capability GitHub offers (I use it with my team every day) and even though translating into some template would be definitely more difficult than translating 2 JSON files 😉 , I am willing to translate it the way you want.

Hi Pavel,

I believe this clunky process is dictated by the way MakeCode works. The "officially included packages" are translated trough https://crowdin.com/ platform. The 3rd party extensions must use the `_locales` method with translations stored in JSON.

I know this, 'cause I'm a contributor / translator of some of the official MakeCode packages and tutorials :-)

**Pull request closed without merging**
